name: han_tok
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  # icon
  cupertino_icons: ^1.0.2
  # get框架
  get: 4.6.5
  # 网络请求
  dio: ^4.0.6
  # 常用工具类
  flustars: ^2.0.1
  # 加载框
  flutter_easyloading: ^3.0.5
  # 屏幕适配
  flutter_screenutil: ^5.6.0
  # 百度地图
  flutter_bmflocation: ^3.3.0
  flutter_baidu_mapapi_base: ^3.3.0
  flutter_baidu_mapapi_map: ^3.3.0
  # 权限处理
  permission_handler: ^10.2.0
  # 文件权限
  path_provider: ^2.0.12
  # 使用svg图标
  flutter_svg: ^1.1.6
  # 国家地区选择器
  country_calling_code_picker: ^2.0.1
  # 图片选择器
  images_picker: ^1.2.11
  image_picker: ^0.8.6
  # 获取设备信息
  device_info_plus: ^4.0.3
  # 插件选择器
  flutter_pickers: ^2.1.8
  # 城市选择器
  city_pickers: ^1.1.3
  # 生成二维码
  qr_flutter: ^4.0.0
  # 文件计算
  filesize: ^2.0.1
  # 打开设置
  app_settings: ^4.1.8
  # md5加密
  crypto: ^3.0.2
  # 基础的点击
  tapped: ^2.0.0
  # 视频播放器
  video_player: ^2.4.7
  # map取值
  safemap: ^2.1.0
  # 带指示器弹窗
  popover: ^0.2.8
  # 扫描
  scan: ^1.6.0
  # 点赞特效
  like_button: ^2.0.5
  # 保存图片
  image_gallery_saver: ^1.7.1
  gallery_saver: ^2.3.2
  # 视频缩略图
  video_thumbnail: ^0.5.3
  # 相机
  camera: ^0.10.3
  # 手电筒控制
  torch_light: ^1.0.0
  # 相册管理
  photo_manager: ^2.5.2
  # 视频压缩
  video_compress: ^3.1.2
  # 下拉框
  dropdown_button_plus: ^0.0.2
  # widget转图片
  widget_to_image: ^2.0.0
  # 国际化
  flutter_localizations:
    sdk: flutter
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/QQ1.svg
  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
