name: han_tok
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  # icon
  cupertino_icons: ^1.0.2
  # get框架
  get: 4.6.5
  # 网络请求
  dio: ^4.0.6
  # 常用工具类
  flustars: ^2.0.1
  # 加载框
  flutter_easyloading: ^3.0.5
  # 屏幕适配
  flutter_screenutil: ^5.6.0
  # 国际化
  flutter_localizations:
    sdk: flutter
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/QQ1.svg
  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
